version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: db_services_auth_api
        APP: services-auth-api
    networks:
      - local
    depends_on:
      - db_services_auth_api
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_services_auth_api
    volumes:
      - ../../..:/code

  db_services_auth_api:
    ports: []
